doc/installation.rst
doc/overview.rst
ephyviewer/version.py
setup.py

release 1.0.0

---

ephyviewer/traceviewer.py

Increase float precision for TraceViewer

---

ephyviewer/epochencoder.py
ephyviewer/epochviewer.py
ephyviewer/spiketrainviewer.py
ephyviewer/timefreqviewer.py
ephyviewer/traceviewer.py

Fulfillment of https://github.com/NeuralEnsemble/ephyviewer/pull/14#issuecomment-420549984, only 8 months late!

Allow user to change vline color

---

ephyviewer/epochencoder.py
ephyviewer/epochviewer.py
ephyviewer/spiketrainviewer.py
ephyviewer/traceviewer.py

I plan to use this for a light mode / dark mode switch in my scripts. 🌑🌒🌓🌔🌕

Add param for setting background fill color of channel labels

---

ephyviewer/dataframeview.py

This is really the same issue as #54, I just forgot to fix the DataFrameView too.

Fix clicking on current selection in DataFrameView

---

ephyviewer/datasource/neosource.py

@samuelgarcia, since this was a simple thing to add, I'm wondering if you had a reason for leaving this out. Your comment that I removed suggested you might have been thinking of doing something more complicated. I'm finding the naive solution performs very well for my data sets. Perhaps you had concerns about performance?

Appropriately rescale raw signals in AnalogSignalFromNeoRawIOSource

---

ephyviewer/traceviewer.py

Fixes #58.
Added new `raw_gains` and `raw_offsets` to `TraceViewer_ParamController`, which are distinguished from the adjustable `gains` and `offsets` parameters. For raw signal sources, these values are obtained from the RawIO header. For in-memory signal sources, `raw_gains` = 1 and `raw_offsets` = 0.
New properties `total_gains` and `total_offsets` are added which provide the combined raw and adjustable gains and offsets. In the case of `total_offsets`, this is not simply the sum as you might expect (see detailed comments for explanation).
Parameters to functions that require the total gains and offsets (`get_data` and `on_request_data`) were renamed to avoid confusion.
Distinguishing between raw and adjustable gains and offsets makes it easier to properly place the trace labels and …

Fix trace label and baseline placement for RawIOs with non-zero offset

---

doc/releases/1.1.0.rst
ephyviewer/traceviewer.py

Fix crash when scatter plot channels are hidden

---

doc/releasenotes.rst

Remember to include latest release notes in list!

---

ephyviewer/epochencoder.py

If the user adds, deletes, or changes any epochs and doesn't save manually before closing, they will be presented with the prompt asking if they want to save. Otherwise, if the user did nothing, or if they saved more recently than their last operation, the prompt will be skipped.
The code isn't smart enough to tell if an operation, such as merging, had no effect, and will always assume there are unsaved changes whenever an operation is executed.

Prompt at exit to save EpochEncoder only if user did something

---

LICENSE
MANIFEST.in

I'm adding the license to the source distribution (tar file on PyPI). I noticed the license was out of date and inaccurately attributed, so I updated it too. @samuelgarcia, are you OK with my changes? Should your institution be credited instead?

Update license and include in source distribution

---

ephyviewer/traceviewer.py

Prior behavior was that trace labels were centered on the zero baseline. Since the zoom feature expands/contracts a signal around its median, this could shift the label out of view if the median was different from zero.
After this change, trace labels are centered on signal medians and remain stationary while zooming.

Prevent trace labels from moving when zooming

---

README.md
doc/installation.rst

Add conda-forge install instructions, update README badges

---

ephyviewer/spiketrainviewer.py

Line height is adjustable with ``scatter_size``. Line width is not adjustable.

Add scatter_size param to SpikeTrainViewer

---

ephyviewer/traceviewer.py

Small fix when on signal is displayed and so the median cannot be estimated.

Small fix when on signal is displayed and so the median cannot be estimated.

---

ephyviewer/epochencoder.py

Display EpochEncoder shortcut keys as y-axis tick mark labels

---

ephyviewer/datasource/epochs.py
ephyviewer/epochencoder.py

Allow new EpochEncoder labels to be created from the options window

---

ephyviewer/epochencoder.py

Group and relabel EpochEncoder's time range selector controls

---

ephyviewer/epochencoder.py

These changes result in _dramatically_ improved performance in updating the EpochEncoder table when the number of epochs is large. Now all epoch changes should be very fast, regardless of the number of epochs.
Prior to this change, QPushButtons and QComboBoxes in every row of the EpochEncoder's table were destroyed and re-created with every table refresh, which is very expensive.
These elements have all been replaced with QTableWidgetItems, which are much faster. QIcons are now created just once at initialization instead of once for each row, each refresh. When a label cell is clicked, it is replaced with a combo box, so labels can still be changed in this way:

Dramatically improve EpochEncoder performance when there are many epochs

---

ephyviewer/epochencoder.py

Add button for creating new labels to the EpochEncoder toolbar

---

ephyviewer/tools.py
ephyviewer/traceviewer.py

Fix TraceViewer scatter points changing color randomly with pyqtgraph 0.11.1

---

MANIFEST.in
doc/releasenotes.rst
doc/releases/1.4.0.rst
ephyviewer/version.py
setup.py

Prepare release 1.4.0

---

ephyviewer/datasource/__init__.py
ephyviewer/datasource/signals.py
ephyviewer/datasource/spikeinterfacesources.py
ephyviewer/tests/test_datasource.py
ephyviewer/tests/test_spikeinterfaceviewer.py
requirements-tests.txt

Implement signals source and spike source for spikeinterface objects:
* Recording (signals)
* Sorting (spikes)

Implement signals source and spike source for spikeinterface objects

---

ephyviewer/datasource/neosource.py
ephyviewer/tests/test_datasource.py

Add back channel_indexes in AnalogSignalFromNeoRawIOSource after neo 0.10
#156

Add back channel_indexes in AnalogSignalFromNeoRawIOSource

---

.github/workflows/tests.yml
ephyviewer/epochencoder.py
ephyviewer/spectrogramviewer.py
ephyviewer/spiketrainviewer.py
ephyviewer/timefreqviewer.py
ephyviewer/traceviewer.py

@jpgill86
Hi Jeffrey.
This fix a bug with latest pyqtgraph version.
I will make a relase today also because I organise a course in my lab next week and need ephyviewer for teaching.

Fix self.vline.setPen(color=...) problem with matest pyqtgraph version.

---

ephyviewer/tests/test_traceviewer.py

neo.AnalogSignal remove copy
