NeuralEnsemble/ephyviewer

ephyviewer/epochencoder.py, ephyviewer/epochviewer.py, ephyviewer/spiketrainviewer.py
When a TraceViewer was vertically stacked in a window with an EpochViewer or a SpikeTrainViewer, their time axes would not align perfectly because the TraceViewer's time axis had no padding whereas the others did. This change fixes that.
=> Removed x-padding for EpochViewer, EpochEncoder, and SpikeTrainViewer

ephyviewer/epochencoder.py, ephyviewer/epochviewer.py, ephyviewer/spiketrainviewer.py, ephyviewer/timefreqviewer.py, ephyviewer/traceviewer.py
Some viewers had a fully opaque green vline (#00FF00). Others had a nearly transparent green vline (#00FF0055) that was difficult to see under some conditions. This commit makes vlines in all viewers have an intermediate alpha level (#00FF00AA) for best viewing.
My colleagues are always impressed when I show off ephyviewer at meetings, but they complained that they couldn't see the vline for the TraceViewer since it was too faint on the projector.
=> Standardize opacity, color, and z-order for vline marking current time for all viewer

ephyviewer/base.py, ephyviewer/epochencoder.py, ephyviewer/epochviewer.py, ephyviewer/mainviewer.py, ephyviewer/spiketrainviewer.py, ephyviewer/timefreqviewer.py, ephyviewer/traceviewer.py
Code for dragging the right mouse button to adjust `xsize` (time zoom) was confined to `TraceViewer`. The first commit (c78fcb7) moves that code to base classes and adds signal connections for `EpochEncoder`, `EpochViewer`, and `SpikeTrainViewer`. Time zoom could be added to `TimeFreqViewer` (see commented out code), but performance is very poor, so this was not added.
In the second commit (f6179b2), `MainViewer` has a new boolean option called `global_xsize_zoom` (default False). When True, dragging the right mouse button to adjust the `xsize` (time zoom) in one viewer will make the same adjustment simultaneously in all viewers.
=> Add time zoom to other viewers, add global time zoom

ephyviewer/traceviewer.py
The new `scatter_size` param for `TraceViewer` controls the size of scatter plot points (drawn only when the source is an `AnalogSignalSourceWithScatter`). The parameter can be set at initialization (`TraceViewer(..., scatter_size=5)`) and using the global options window (double click on trace window).
=> Add scatter_size as an adjustable parameter to TraceViewer

ephyviewer/base.py, ephyviewer/mainviewer.py
I find that the xsize zoom feature is too sensitive when zooming in. Often I will move a little too quickly and the xsize will shrink instantly to a microsecond. The first of these commits prevents that from happening by slowing the xsize reduction rate. I think it's still plenty fast. The zoom out rate (xsize increasing) is unchanged.
The second commit fixes the `global_xsize_zoom` option, which previously did not update the xsize spinbox in the navigation widget.
=> Fixes for xsize zoom

ephyviewer/navigation.py
pyqtgraph allows unit abbreviations to be appended to spinboxes as suffixes. However, this makes changing the numbers in the spinboxes more difficult. For the time and xsize spinboxes, the "s" for seconds cannot be temporarily deleted while typing in the box. If the cursor is placed behind the suffix, the backspace key will not work. The user has to be very careful to place their cursor in front of the "s" before they can make changes.
The first of these commits drops the suffixes entirely. The second commit adds properly formatted labels for the spinboxes (and the auto scale button), including indicators of the time units.
=> Remove "s" suffixes from navigation spinboxes for time and xsize

ephyviewer/navigation.py
Convenient key bindings for stepping through time with the left and right arrow keys already exist. The first commit adds new key bindings for increasing (Shift+right arrow) and decreasing (Shift+left arrow) the step size. The second commit adds a couple smaller step sizes to the list.
=> Shortcuts for changing the navigation step size

ephyviewer/traceviewer.py
The lines in the TraceViewer can be difficult to see under some conditions, such as when using a projector during a presentation. This commit adds a new option for adjusting the line widths in the TraceViewer.
Unfortunately, any value greater than 1.0 pixel has _extremely_ poor performance on my system, making it infeasible to play through the data with a greater line width. This feature isn't useful for that, but it may be useful to others for static displays, such as screenshots.
I haven't investigated the cause of the poor performance. I'd speculate that the problem is with pyqtgraph, not ephyviewer. Perhaps this can be optimized somehow.
=> Add line-width option to TraceViewer

ephyviewer/datasource/video.py
Some videos (e.g. screen recordings made with old versions of QuickTime Player) have stream.start_time = None, which causes seek to fail. This commit provides 0 as a fallback offset parameter for seek.
=> Fix for video streams lacking start_time

ephyviewer/datasource/video.py, ephyviewer/videoviewer.py
Since PyAV 0.5.3 (Oct 2018) and 6.1.0 (Nov 2018), ephyviewer's video source and video viewer classes have generated deprecation warnings. This PR updates the function calls so that the deprecation warnings are no longer raised.
Because PyAV's API changes were not made backwards compatible, the changes introduced here to ephyviewer are wrapped in a `try` statement to allow ephyviewer to remain backwards compatible with older versions of PyAV.
=> Address PyAV deprecation warnings

ephyviewer/datasource/video.py
`get_frame` was sometimes called with a `target_frame` greater than the last frame index. This could occur when dragging the navigation slider all the way to the end, or when trying to step beyond the end of the video. This caused `get_frame_absolut_seek` to spend 250 iterations in its `reseek` loop, and the video would freeze for many seconds until this loop completed.
This commit adds a check to `get_frame`: if the `target_frame` exceeds the final frame index, the final frame is fetched instead.
=> Fix for seeking non-existent video frames beyond end of video

ephyviewer/epochencoder.py
The controls for the EpochEncoder can take up a lot of screen space, and sometimes it would be convenient to just hide them while you aren't using them. This PR adds a toggle for collapsing the controls.
Controls showing:
Controls collapsed:
=> Add button to EpochEncoder for collapsing controls

ephyviewer/datasource/video.py
`MultiVideoFileSource.time_to_frame_index` can determine the frame index in one of two ways: (1) The timing of each frame can be inferred from the video rate and start time (assuming regular timing), or (2) arbitrary frame timing can be explicitly provided in `video_times`.
In the first case, the frame index is computed as
```python
frame_index = int((t-self.t_starts[i])*self.rates[i])
```
__This has the effect of always rounding down:__ If `t` is between frames, the index of the frame __before__ `t` will be returned.
In the second case, the frame index is computed as
```python
frame_index = np.searchsorted(self.video_times[i], t)
```
__This has the effect of always rounding up:__ If `t` is between frames, the index of the frame __after__ `t` will be returned. This is because …
=> Ensure time_to_frame_index always returns the frame preceding t

ephyviewer/datasource/video.py
`get_frame` was sometimes called with a negative `target_frame`. This could occur when the video's `t_start` was positive, or if `video_times` began with positive values. Like the bug fixed by 535ba9a, this caused `get_frame_absolut_seek` to spend 250 iterations in its `reseek` loop, and the video would freeze for many seconds until this loop completed.
This commit adds a check to `get_frame`: if the `target_frame` is negative, the first frame is fetched instead.
The commit also moves the comparison to `last_frame_index` to the beginning for optimization.
=> Fix for seeking non-existent video frames before start of video

ephyviewer/datasource/video.py, ephyviewer/videoviewer.py
When `target_frame` is negative or greater than largest frame index, `get_frame` will return None instead of the first or last frame. When `update_frame` is called with `frame=None`, it clears the image.
=> Clear video image when t is before the start or after the end of video

ephyviewer/mainviewer.py, ephyviewer/traceviewer.py
The standalone app would crash if the signals did not begin at t=0, but instead started after t=2.1. This occurred because `compose_mainviewer_from_sources` would try to `auto_scale` before the first signal was added to the window. Before any viewers are added to the window, the time is initially set to 0 with `xsize` = 3. Thus the right edge of the view is t=2.0999. Attempting to `auto_scale` a signal that has no data points within the window causes a crash because `get_chunk` returns an empty list. `compute_rescale` checked that the list was not None, but not that it wasn't empty, so it attempted to compute statistics on an empty list.
This commit fixes the issue by first catching the empty list case, and second by having the standalone app auto scale only after the trace viewer has …
=> Fix for standalone crash when signals start after t=2.1

ephyviewer/datasource/epochs.py
Epochs with end times precisely equal to t_stop were not being retrieved by either `InMemoryEpochSource.get_chunk_by_time` or `WritableEpochSource.get_chunk_by_time`.
=> Fix for getting epochs that end exactly at t_stop

ephyviewer/navigation.py
I added more ergonomic shortcuts on the left side of the keyboard for stepping through time and changing the step size.
I also changed the old Shift+Right and Shift+Left bindings (first added in d891a48) to Up and Down to mirror the new WASD bindings.
I originally chose the Shift-modified bindings because I wanted to allow Up and Down to change epoch labels in the EpochEncoder (first added in e01f1ba). That worked really well but isn't a feature I use nearly as often as I change the nav step size. Up and Down seem pretty intuitive to me, so I'd like to start using them for that.
@samuelgarcia, are you OK with these changes? Or do you prefer something else?
=> WASD navigation shortcuts

ephyviewer/base.py, ephyviewer/myqt.py, ephyviewer/traceviewer.py
Fixes #34.
This performance issue clearly isn't confined to ephyviewer, as the same issue has been [reported for pyqtgraph](https://github.com/pyqtgraph/pyqtgraph/issues/533) and [Qt itself](http://www.qcustomplot.com/index.php/support/forum/1008). The solution I'm trying in this PR was proposed by @campagnola here: https://github.com/pyqtgraph/pyqtgraph/issues/533#issuecomment-388932019.
I don't want to merge this immediately. I'd like to try it out for a couple days to see if there are any new problems. I don't really understand the full implications of enabling OpenGL, and [the pyqtgraph docs here](http://www.pyqtgraph.org/documentation/config_options.html) leaves me feeling a little nervous; "`useOpenGL | bool | False | Enable OpenGL in GraphicsView. This can have unpredictable …
=> Fix poor performance when TraceViewer's line_width > 1.0

ephyviewer/traceviewer.py
For TraceViewer, after zooming time in such that only a few points are visible, the curves would end before reaching the right edge of the viewer. If the user zoomed in more, the ends of the lines would eventually travel off the left edge of the viewer and cease to be visible. This was caused by `DataGrabber.get_data` grabbing too few points when it needed to grab some extras outside the visible plot range to ensure curves continued across the entire plotted range. This commit fixes this so that the curves continue across the viewer no matter how much the user zooms in time.
I expected I would need to add 1 to `i_stop`, not 2, but I can tell you that, empirically, it required 2. I don't know why exactly! `BaseAnalogSignalSource.time_to_index` rounds down and returns the last index before …
=> Fix TraceViewer drawing incomplete curves when zoomed in

ephyviewer/base.py
The `mouseDragEvent` triggered when the mouse was dragged in any of the viewers' axes included an unhandled keyword `axis`. This raised a non-fatal TypeError. This commit handles the keyword by ignoring it, which eliminates this error.
=> Fix error when dragging mouse on viewer axes

ephyviewer/epochencoder.py
In EpochViewer, opaque colors are assigned to rectangle borders, and a transparent version of the color is assigned to the rectangle fill. In EpochEncoder, the border was always white, and the interior was the opaque color. This commit changes EpochEncoder to determine colors the same way as EpochViewer.
This is motivated by the new "light mode"/"light theme" I'm building for myself, which has a light colored background in each panel. The old coloring of EpochEncoder had all white borders, which was difficult to see against a light background. And since the border becomes the only thing you can see if the rectangles are small relative to xsize, I had EpochEncoder rectangles basically disappearing against the light background. This change makes EpochEncoder and EpochViewer consistent with …
=> Use same color determination for EpochEncoder rectangles as EpochViewer

ephyviewer/traceviewer.py
The objective of the code removed by this commit was to keep the medians of the signals fixed in place as ygain was zoomed in or out under `by_channel` or `same_for_all` scale modes. However, because the median is only estimated from a randomly selected subset of samples and also changes from chunk to chunk, this makes ygain zoom in these modes a non-reversible operation, i.e., zooming in and then zooming out does not return you to the same configuration. Instead, the offsets of the signals can drift away from their original locations and the signals can even move out of view, like this:
Notice that the channel labels, which are anchored to the offsets, move around during zooming. After zooming out again the channel spacing is not the same as it was before, and the bottom gray trace has …
=> Don't adjust offsets in apply_ygain_zoom for TraceViewer

ephyviewer/base.py
The `wheelEvent` triggered when the mouse was scrolled in any of the viewers' axes included an unhandled keyword `axis`. This raised a fatal TypeError. This commit handles the keyword by ignoring it, which eliminates this error.
This bug and its solution are both very similar to #51.
=> Fix error when scrolling mouse on viewer axes

ephyviewer/epochencoder.py, ephyviewer/eventlist.py
Selecting items in the EventList or EpochEncoder table would jump time to the start of the event/epoch, unless the clicked item was already selected. In the case of lists/tables containing only one item, there was no way to unselect an item, so in these cases it was impossible to use this feature again after the first use.
This commit changes the trigger for jumping from changing the selection to simply clicking on an item. This allows the user to easily jump to the currently selected item if they have scrolled away from it.
=> Fix clicking on current selection in EventList and EpochEncoder table

ephyviewer/datasource/neosource.py, ephyviewer/traceviewer.py
This PR is a response to #44 and is what I was referring to here: https://github.com/NeuralEnsemble/ephyviewer/pull/44#issuecomment-498045709
=> Rescale raw signals only in real_scale mode

ephyviewer/datasource/neosource.py, ephyviewer/traceviewer.py
If `AnalogSignalFromNeoRawIOSource.channel_indexes` was a subset of channels, instead of all channels, the wrong gains and offsets were fetched and a crash would occur.
=> Fix real_scale for raw signals when channel_indexes is a subset

ephyviewer/tests/testing_tools.py
Before this fix, I would get this:
```
(py3) C:\Users\Jeffrey\Documents\python-dev>python ephyviewer\git-repo\ephyviewer\examples\mixed_viewer.py
make_video_file video0.avi
Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Traceback (most recent call last):
File "ephyviewer\git-repo\ephyviewer\examples\mixed_viewer.py", line 12, in <module>
video_source = make_fake_video_source()
File "c:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\tests\testing_tools.py", line 109, in make_fake_video_source
make_video_file(filename, )
File "c:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\tests\testing_tools.py", line 94, in make_video_file
packet = stream.encode(None)
File "av/stream.pyx", …
```
=> Catch make_video_file crash

ephyviewer/epochencoder.py
Previously, pressing a shortcut key for the epoch encoder (default: number keys) would always create a new epoch beginning at the current time with a duration determined by the `new_epoch_step` parameter. This commit adds additional functionality. If the range selector is active, pressing a shortcut key will fill the range with a new epoch with the corresponding label. If the range selector is not active, the old behavior using `new_epoch_step` is used.
=> Allow epoch encoder shortcuts to apply labels to selected range

ephyviewer/navigation.py
Prior to this commit, the string format defaulted to ``datetime.isoformat(sep=' ', timespec='auto')``, which displayed with microseconds as ``YYYY-MM-DD HH:MM:SS.ffffff`` or, if microsecond was 0, ``YYYY-MM-DD HH:MM:SS``. This resulted in the datetime label changing width depending on the time.
The new default format string drops microseconds entirely. I assume that level of precision for real-world time is neither necessary nor accurate in the majority of cases. Users can get microseconds back by changing the new parameter.
=> Add a parameter to NavigationToolBar for setting datetime string format

ephyviewer/traceviewer.py
Although the [pyqtgraph docs say](http://www.pyqtgraph.org/documentation/widgets/spinbox.html#pyqtgraph.SpinBox.setOpts) that the ``decimals`` option for SpinBox defaults to 6, the behavior differs if that value is provided vs not provided.
Without any value specified, I find that the SpinBoxes for the gains in the TraceViewer switch to scientific notation with values as small as 1000. This is represented as "1e+03". This makes modifying the value much more difficult, because the SpinBox does not actually permit you to enter scientific notation. For example, if you wanted to double the gain, you can't just change "1e+03" to "2e+03". That will be interpreted as 2 instead of 2000 because the "e" and everything after it is dropped.
With ``decimals`` set to 6, I can go all the way up to …
=> Use scientific notation in TraceViewer gain spin boxes less often

doc/interface.rst, ephyviewer/traceviewer.py
This PR adds two mouse interactions for the TraceViewer:
* Left-click and drag on a trace label to change its offset, allowing the user to move a trace up or down easily.
* In ``by_channel`` scale mode only, scroll the mouse wheel on a trace label to rescale just that trace, rather than all traces at once. This feature is disabled in ``real_scale`` and ``same_for_all`` scale modes.
The second feature may be a little difficult to use for labels that move a lot when the gain is changed. This is most likely to occur for signals that aren't centered on zero, like intracellular voltages.
=> Add TraceViewer label mouse events for adjusting gains and offsets

doc/interface.rst, ephyviewer/epochencoder.py
Pressing ``r`` toggles the range indicator. Pressing ``[`` or ``]`` will set the left or right edge of the range indicator, respectively.
These new shortcuts are especially convenient when the EpochEncoder's controls are hidden. In combination with the label shortcuts (numbers), power users can perform most actions even with the controls hidden.
=> Add EpochEncoder shortcuts for toggling range, setting left/right limits

doc/interface.rst, ephyviewer/epochencoder.py
``Ctrl+s``, or ``Cmd+s`` on Mac
=> Add EpochEncoder shortcut for saving

ephyviewer/traceviewer.py
Increasing/decreasing the value of the new ``auto_scale_factor`` parameter causes the "Auto scale" feature to make the traces bigger/smaller in ``same_for_all`` and ``by_channel`` scale modes.
=> Add auto_scale_factor param to TraceViewer

ephyviewer/datasource/video.py
Some video files (I do not understand all the relevant conditions) may crash when seeking near the last frame:
```
Traceback (most recent call last):
File "c:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\videoviewer.py", line 99, in on_request_frame
frame = self.fg.get_frame(target_frame)
File "c:\users\jeffrey\documents\python-dev\ephyviewer\git-repo\ephyviewer\ephyviewer\datasource\video.py", line 114, in get_frame
if frame_index >= target_frame:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
This change is intended to fix that issue.
However, I don't feel great about this one because I understand neither the root cause of the crash nor why my fix is _not_ a terrible idea. I expected ``frame_index is None`` to be a bad state …
=> Fix error when frame_index is None

ephyviewer/epochviewer.py
The wrong indexing variable was used, causing the wrong colors to be applied to channels listed after any hidden channels.
=> Fix EpochViewer colors when some channels are not visible

ephyviewer/spiketrainviewer.py
Fixes a plot range bug for SpikeTrainViewer introduced in 6ac5279 (since v1.2.1). Fixes #94.
Spike times are now plotted with ``pxMode=False``, so their size, specified by ``scatter_size``, is now given in the plot coordinate system, rather than pixels. This allows automatic plot range padding to be computed more intelligently. Resizing a SpikeTrainViewer panel will no longer cause the relative gaps between rows in the raster plot to change. Adjusting ``scatter_size`` will adjust the gap between rows.
=> Fix plot range for SpikeTrainViewer when only one channel is visible

ephyviewer/epochencoder.py, ephyviewer/epochviewer.py, ephyviewer/spiketrainviewer.py, ephyviewer/timefreqviewer.py, ephyviewer/traceviewer.py
The parameter may vary between 0 and 1 and controls the fraction of the displayed data that is in the "past", preceding the current time. Default: 0.3.
With xratio set to 1, all displayed data precedes the current t, so only "past" data is shown. With xratio set to 0, all displayed data follows the current t, so only "future" data is shown.
=> Add xratio parameter to viewers for controlling vline position

ephyviewer/epochencoder.py
This change prevents the range's lower bound from being set to a value greater than its upper bound using the spin boxes, and vice versa.
=> Fix bounds of EpochEncoder time range selector's spin boxes

ephyviewer/epochencoder.py
This is a fix for a bug introduced in a different fix (#106). That's the way it goes sometimes...
The spin box bounds needed to be updated when the time range was adjusted by means other than the spin boxes, such as by dragging the region with the mouse.
Hopefully I've got it all fixed now!
=> Again fix bounds of EpochEncoder time range selector's spin boxes

ephyviewer/epochencoder.py
Label column was sometimes too narrow if labels were long.
=> Fix column widths for buttons and labels in EpochEncoder table

ephyviewer/epochencoder.py
All buttons and controls originally in the left column ("Options", "Merge neighbors", "Fill blank", "Epoch insertion mode", "Save") have been moved into a toolbar at the bottom of the EpochEncoder, along with the "Hide controls"/"Show controls" button. Additionally, internal margins, as well as button widths in the table, were made smaller.
These changes greatly improve the amount of space available for the table. This was especially needed on macOS, where the default margins and padding for all control elements are excessively big.
Before (notice table does not fit):
> ![image](https://user-images.githubusercontent.com/241234/95040754-92a9c400-06a2-11eb-9fe3-edf2dfc711a3.png)
After (table fits easily, and new toolbar at bottom):
> …
=> Reorganize EpochEncoder controls to reduce crowding

ephyviewer/epochencoder.py, ephyviewer/navigation.py
pyqtgraph 0.11.0 introduced the `compactHeight` parameter for spin boxes, which is on by default. This was intended to reduce excessive vertical white space within spin boxes, but I find that it overcompensates and makes them look worse (or at least no better) across platforms (checked Windows 10, macOS, and Ubuntu).
Here are examples from Ubuntu, where the numbers inside the spin boxes were being clipped:
Before:
> ![image](https://user-images.githubusercontent.com/241234/95041812-c803e100-06a5-11eb-89b2-24f2335b5293.png)
After:
> ![image](https://user-images.githubusercontent.com/241234/95041896-04374180-06a6-11eb-9a92-c893127e1666.png)
=> Prevent overzealous spin box height correction in pyqtgraph 0.11.0

.gitignore, ephyviewer/datasource/neosource.py
Simple change to use new get_group_signal_channel_indexes in Neo 0.9.0 release.
=> Fix signal grouping in get_sources_from_neo_rawio() for Neo 0.9.0

ephyviewer/epochencoder.py
A back-of-the-envelope calculation as well as actual tests suggests that, for a very large set of 600 epochs with moderately short labels, the undo history would not grow to 10 MB until it reached a depth of about 500 steps. Seems reasonable to me!
=> Increase EpochEncoder's undo_history_size default value

ephyviewer/scripts.py, ephyviewer/standalone.py, ephyviewer/tests/test_standalone.py
Closes #122.
`StandAloneViewer` was replaced by `WindowManager`, which handles spawning a new `MainViewer` each time the Open menu action is used. `WindowManager` also cleans up file locks and deallocates memory when a `MainViewer` is closed.
Additionally, when the app is run from the command line without arguments, the `RawNeoOpenDialog` is launched immediately, rather than the user being required to launch it manually with the Open menu action.
Finally, many of the command line interface's help and error messages have been improved.
=> Allow standalone app to open multiple files, each in independent windows

ephyviewer/tools.py
Fixes #124.
pyqtgraph 0.11.0 added the connection and disconnection of a signal to `GraphicsLayout.addItem` and `GraphicsLayout.removeItem`, respectively. ephyviewer's `create_plot_grid` was bypassing the initial connection by calling not `GraphicsLayout.addItem`, but `GraphicsLayout.layout.addItem` instead. When `GraphicsLayout.removeItem` was later used, the signal disconnection step raised an error because the signal was never connected in the first place.
This change makes sure the correct `addItem` method is called, so that the signal is initially connected.
=> Fix `'method' object is not connected` error for TimeFreqViewer

ephyviewer/epochencoder.py
Fixes #115.
Why this is needed at all, and especially why so on just one platform, is a mystery to me. Possibly caused by a macOS-specific implementation detail in Qt/PyQt...
=> Force repaint of EpochEncoder's spin boxes after use of "Set start"/"Set stop" buttons

ephyviewer/epochencoder.py
Adjusting an epoch start time in the EpochEncoder table will now cause its duration to change while maintaining its stop time (i.e., shorten or lengthen the epoch = new behavior), rather than causing its stop time to change while maintaining its duration (i.e., shifting the epoch forward or backward in time = old behavior).
In my experience, this new behavior is usually what users intend when they change the start time.
=> Stretch instead of shift epoch when start time is edited in EpochEncoder table

.github/workflows/tests.yml, doc/installation.rst, ephyviewer/datasource/epochs.py, requirements-docs.txt, requirements.txt, setup.py
This pull request adds a minimal GitHub Actions workflow file which
1. Tests that the docs can be build, and
2. Tests that the package can be installed with `pip install .` and that `import ephyviewer` works afterward.
Note that this does not actually run any of the tests in `ephyviewer/tests`! Those tests will require tweaking to run without human interaction (at minimum, `app.exec_()` will need to be removed in many places, but it might also be useful to keep versions that can be run by a human for viewing the results).
=> Add minimal GitHub Actions workflow for testing installation, importing the package, and building the docs

.github/workflows/publish-to-pypi.yml, .github/workflows/publish-to-test-pypi.yml
We will be able to run these workflows manually from the [GitHub Actions](https://github.com/NeuralEnsemble/ephyviewer/actions) page. For now, until I grow to trust it, I prefer triggering manually rather than on pushing a tag. Perhaps after the next release I will feel comfortable with it. 😁
@samuelgarcia, I think only you will be able to add the PyPI secret tokens to this repo. We are co-maintainers of the [official PyPI project](https://pypi.org/project/ephyviewer/), but only I am a maintainer of the [TestPyPI project](https://test.pypi.org/project/ephyviewer/) (I could add you if you like; you may need to create an account first). So, I've taken the initiative to generate tokens for both projects. I will email them to you so that you can add them to this repo's [GitHub secrets …
=> Add manually-triggerable GitHub Action workflows for publishing to PyPI

ephyviewer/tests/test_mainviewer.py
Forgetting `interactive=True` for two tests was a mistake.
=> Enable interactivity when running test_mainviewer.py manually

.github/workflows/tests.yml
Using cached files instead of downloading them can shave up to a couple minutes off the time it takes for the tests to complete.
=> Cache Neo data files used for testing on GitHub Actions

ephyviewer/datasource/neosource.py, ephyviewer/tests/test_datasource.py, requirements-tests.txt
Hi @samuelgarcia,
Here's my revised version of `neosource.py`. It should just work for all versions of Neo since RawIOs were introduced, back to Neo 0.6. I tested each major Neo release using [this Blackrock data set](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/blackrock/segment/PauseCorrect) with the `ephyviewer` CLI, as well as some of my own data sets in *neurotic*.
I don't see any reason at this point to limit support for Neo to 0.8+, since it's working for 0.6 and 0.7.
Tell me what you think!
Closes #158.
=> Make Neo RawIO sources compatible with Neo 0.6-0.10

ephyviewer/mainviewer.py
It was possible to accidentally grab an invisible 1-pixel-tall title bar for the navigation toolbar and drag it out of the main window, causing it to become un-docked, or to tabify it with viewers. This change prevents all movement of the navigation toolbar.
=> Prevent accidental un-docking of the navigation toolbar

ephyviewer/base.py, ephyviewer/datasource/epochs.py, ephyviewer/datasource/signals.py, ephyviewer/spectrogramviewer.py, ephyviewer/timefreqviewer.py
The function has been removed from matplotlib >= 3.9.
Fixes #184
=> Replace deprecated matplotlib get_cmap()

.gitignore
This ignores the PyCharm .idea subdirectory so that changes to it when working with PyCharm will not impact this main project.
=> Ignore PyCharm .idea subdirectory
